services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=mysql.railway.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=railway
      - MYSQL_PORT=3306

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=railway
    ports:
      - "3306:3306"