version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQLHOST=mysql.railway.internal
      - MYSQLUSER=root
      - MYSQLPASSWORD=vnrotqSGIQVLCSwArWfQiKlHyQvNItGQ
      - MYSQLDATABASE=railway
      - MYSQLPORT=48982